FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/src

COPY . /app

RUN pip install --no-cache-dir \
    pandas \
    pydantic \
    psycopg[binary] \
    sqlalchemy \
    python-dotenv

CMD ["python", "/app/src/scripts/wait_for_db.py", "python", "/app/src/consumer/main.py"]
